export const S3_ACCESS_KEY = 'AKIAIS227YKKN6F7JX4A';
export const S3_SECRET_ACCESS_KEY = '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';

export const REKOGNITION_ACCESS_KEY = 'AKIAIKTIQARXO675KYIQ';
export const REKOGNITION_SECRET_ACCESS_KEY = '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';